{
 "title": "FoxesDrbd",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(drbdreactor_up, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "DRBD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of DRBD Resources",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "drbd_resource_resources{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 } },
  {
   "title": "Scrape Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(scrape_duration_seconds{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DRBD Resources Out of Sync",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(drbd_peerdevice_outofsync_bytes{instance=~\"$instance\"}) by(name, instance) > 0"
    }
   ]
  },
  {
   "title": "DRBD out-of-sync",
   "type": "graph",
   "description": "DRBD data out of sync with a peer",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "drbd_peerdevice_outofsync_bytes{instance=~\"$instance\"} > 0",
     "legendFormat": "{{name}} on {{instance}}"
    }
   ]
  },
  {
   "title": "Standalone DRBD resources",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "drbd_connection_state{drbd_connection_state=~\"!UpToDate\", instance=~\"$instance\"} == 1",
     "legendFormat": "{{name}} {{instance}}"
    }
   ]
  },
  {
   "title": "Number of unintentional diskless resources",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "drbd_device_unintentionaldiskless == 1",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DRBD Resources Without Quorum",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "count(drbd_device_quorum{instance=~\"$instance\"} == 0) by(instance, name)"
    }
   ]
  },
  {
   "title": "Number of Resources Without Quorum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(drbd_device_quorum{instance=~\"$instance\"} == 0)",
     "legendFormat": "{{name}} on {{instance}}"
    }
   ]
  },
  {
   "title": "Write Rate (5 Most Active Volumes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(drbd_device_written_bytes_total{instance=~\"$instance\"}[5m]) and topk(5, avg_over_time(drbd_device_written_bytes_total{instance=~\"$instance\"}[6h]) > 0)",
     "legendFormat": "{{name}} on {{instance}}"
    }
   ]
  },
  {
   "title": "Read Rate (5 Most Active Volumes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(drbd_device_read_bytes_total{instance=~\"$instance\"}[5m]) and topk(5, avg_over_time(drbd_device_read_bytes_total{instance=~\"$instance\"}[6h]) > 0)",
     "legendFormat": "{{name}} on {{instance}}"
    }
   ]
  }
 ]
}