FROM almalinux:8
MAINTAINER Roland Kammerer <roland.kammerer@linbit.com>

RUN yum install -y gcc git make rpm-build systemd && \
	curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --profile minimal -y -q --no-modify-path && \
	. "${HOME}/.cargo/env" && \
	yum clean all
